server:
  port: 8007
spring:
  application:
    name: hystrix-provider-payment


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8007
    prefer-ip-address: true
    # eureka客户端向服务端发送心跳的时间间隔，默认是30
    lease-renewal-interval-in-seconds: 5
    #eureka 服务端在收到最后一次心跳后等待的时间上限，默认是90，超时将剔除服务
    lease-expiration-duration-in-seconds: 10