server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment-feign-80
spring:
  application:
    name: payment-feign-80
logging:
  level:
    com.dandelion.springcloud.service.PaymentOrderService: debug

feign:
  httpclient:
    connection-timeout: 2000

ribbon:
  ReadTimeOut: 3000
  ConnectTimeOut: 2000
